In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [ ]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((3,10),int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2)

array([[0.61429555, 0.01448777],
       [0.8742495 , 0.91164124],
       [0.3733242 , 0.62367464]])

In [ ]:
np.random.randn(3,2)

array([[ 0.62996461, -0.48054949],
       [-1.05583622, -0.04142677],
       [-0.38924843,  1.47294356]])

In [ ]:
np.random.randint(1,5)

4

In [ ]:
np.random.randint(34,100,50)

array([39, 90, 90, 83, 43, 95, 43, 67, 50, 41, 55, 48, 50, 95, 43, 36, 52,
       73, 54, 84, 65, 61, 34, 86, 87, 55, 64, 62, 48, 99, 79, 46, 49, 36,
       57, 85, 79, 61, 90, 77, 84, 97, 36, 78, 38, 54, 51, 55, 41, 63])

In [ ]:
sample_array=np.arange(30)

In [ ]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array

array([70, 30, 55, 78, 68, 18, 36, 25, 22, 71, 23, 20, 67, 37, 63, 78, 89,
       66, 60, 59])

In [ ]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

18

In [ ]:
rand_array.argmin()

5

In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.46921731, 0.67317972, 0.1557279 ],
       [0.57632033, 0.49352739, 0.28847897]])

In [ ]:
a.T

array([[0.46921731, 0.57632033],
       [0.67317972, 0.49352739],
       [0.1557279 , 0.28847897]])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[3]

13

In [ ]:
sample_array[3:7]

array([13, 14, 15, 16])

In [6]:
import numpy as np

In [7]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [9]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [11]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [12]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [13]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [15]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [16]:
sample_matrix[0:2,2]

array([ 1, 21])

In [20]:
sample_matrix[:,3]

array([23, 33,  7])

In [21]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [22]:
sample_matrix[2]

array([56, 76, 24,  7])

In [23]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [24]:
sample_array=np.arange(1,20)

In [25]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [26]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [27]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [28]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [29]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [30]:
np.std(sample_array)

5.477225575051661

In [31]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [32]:
np.max(sample_array)

19

In [34]:
np.var(sample_array)

30.0

In [35]:
np.min(sample_array)

1

In [36]:
np.argmin(sample_array)

0

In [37]:
np.argmax(sample_array)

18

In [38]:
np.mean(sample_array)

10.0

In [39]:
array=np.random.randn(3,4)

In [40]:
array

array([[-0.227273  , -0.76065651, -0.31276197,  0.45477763],
       [ 0.91125951,  1.32196241, -1.22991527,  0.94089968],
       [ 0.03134947, -1.94690972, -1.6950757 , -0.69640315]])

In [44]:
np.round(array,decimals=3)

array([[-0.227, -0.761, -0.313,  0.455],
       [ 0.911,  1.322, -1.23 ,  0.941],
       [ 0.031, -1.947, -1.695, -0.696]])

In [45]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')